// // prettier-ignore
// export const buttons = new Set([
//   // Letters
//   'KeyA', 'KeyB', 'KeyC', 'KeyD', 'KeyE', 'KeyF', 'KeyG', 'KeyH', 'KeyI', 'KeyJ',
//   'KeyK', 'KeyL', 'KeyM', 'KeyN', 'KeyO', 'KeyP', 'KeyQ', 'KeyR', 'KeyS', 'KeyT',
//   'KeyU', 'KeyV', 'KeyW', 'KeyX', 'KeyY', 'KeyZ',

//   // Numbers (main keyboard)
//   'Digit0', 'Digit1', 'Digit2', 'Digit3', 'Digit4',
//   'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9',

//   // Function keys
//   // 'F1', 'F2', 'F3', 'F4', 'F5', 'F6',
//   // 'F7', 'F8', 'F9', 'F10', 'F11', 'F12',

//   // Numpad
//   // 'Numpad0', 'Numpad1', 'Numpad2', 'Numpad3', 'Numpad4',
//   // 'Numpad5', 'Numpad6', 'Numpad7', 'Numpad8', 'Numpad9',
//   // 'NumpadAdd', 'NumpadSubtract', 'NumpadMultiply', 'NumpadDivide',
//   // 'NumpadDecimal', 'NumpadEnter', 'NumpadEqual',

//   // Special characters and punctuation
//   'Minus', 'Equal', 'BracketLeft', 'BracketRight', 'Backslash',
//   'Semicolon', 'Quote', 'Backquote', 'Comma', 'Period', 'Slash',

//   // Navigation
//   'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight',
//   'Home', 'End', 'PageUp', 'PageDown',

//   // Control keys
//   'Tab', 'CapsLock', 'ShiftLeft', 'ShiftRight',
//   'ControlLeft', 'ControlRight', 'AltLeft', 'AltRight',
//   // 'MetaLeft', 'MetaRight', 'ContextMenu',

//   // System keys
//   'Enter', 'Space', 'Backspace', 'Delete',
//   // 'Escape', 'PrintScreen', 'ScrollLock', 'Pause',

//   // Media keys
//   // 'MediaPlayPause', 'MediaStop', 'MediaTrackNext', 'MediaTrackPrevious',
//   // 'AudioVolumeMute', 'AudioVolumeDown', 'AudioVolumeUp',

//   // Browser keys
//   // 'BrowserBack', 'BrowserForward', 'BrowserRefresh', 'BrowserStop',
//   // 'BrowserSearch', 'BrowserFavorites', 'BrowserHome'

//   // Custom
//   'MouseLeft', 'MouseRight'
// ])

export const codeToProp = {
  KeyA: 'keyA',
  KeyB: 'keyB',
  KeyC: 'keyC',
  KeyD: 'keyD',
  KeyE: 'keyE',
  KeyF: 'keyF',
  KeyG: 'keyG',
  KeyH: 'keyH',
  KeyI: 'keyI',
  KeyJ: 'keyJ',
  KeyK: 'keyK',
  KeyL: 'keyL',
  KeyM: 'keyM',
  KeyN: 'keyN',
  KeyO: 'keyO',
  KeyP: 'keyP',
  KeyQ: 'keyQ',
  KeyR: 'keyR',
  KeyS: 'keyS',
  KeyT: 'keyT',
  KeyU: 'keyU',
  KeyV: 'keyV',
  KeyW: 'keyW',
  KeyX: 'keyX',
  KeyY: 'keyY',
  KeyZ: 'keyZ',
  Digit0: 'digit0',
  Digit1: 'digit1',
  Digit2: 'digit2',
  Digit3: 'digit3',
  Digit4: 'digit4',
  Digit5: 'digit5',
  Digit6: 'digit6',
  Digit7: 'digit7',
  Digit8: 'digit8',
  Digit9: 'digit9',
  Minus: 'minus',
  Equal: 'equal',
  BracketLeft: 'bracketLeft',
  BracketRight: 'bracketRight',
  Backslash: 'backslash',
  Semicolon: 'semicolon',
  Quote: 'quote',
  Backquote: 'backquote',
  Comma: 'comma',
  Period: 'period',
  Slash: 'slash',
  ArrowUp: 'arrowUp',
  ArrowDown: 'arrowDown',
  ArrowLeft: 'arrowLeft',
  ArrowRight: 'arrowRight',
  Home: 'home',
  End: 'end',
  PageUp: 'pageUp',
  PageDown: 'pageDown',
  Tab: 'tab',
  CapsLock: 'capsLock',
  ShiftLeft: 'shiftLeft',
  ShiftRight: 'shiftRight',
  ControlLeft: 'controlLeft',
  ControlRight: 'controlRight',
  AltLeft: 'altLeft',
  AltRight: 'altRight',
  Enter: 'enter',
  Space: 'space',
  Backspace: 'backspace',
  Delete: 'delete',
  Escape: 'escape',
  MouseLeft: 'mouseLeft',
  MouseRight: 'mouseRight',
}

export const propToCode = {
  keyA: 'KeyA',
  keyB: 'KeyB',
  keyC: 'KeyC',
  keyD: 'KeyD',
  keyE: 'KeyE',
  keyF: 'KeyF',
  keyG: 'KeyG',
  keyH: 'KeyH',
  keyI: 'KeyI',
  keyJ: 'KeyJ',
  keyK: 'KeyK',
  keyL: 'KeyL',
  keyM: 'KeyM',
  keyN: 'KeyN',
  keyO: 'KeyO',
  keyP: 'KeyP',
  keyQ: 'KeyQ',
  keyR: 'KeyR',
  keyS: 'KeyS',
  keyT: 'KeyT',
  keyU: 'KeyU',
  keyV: 'KeyV',
  keyW: 'KeyW',
  keyX: 'KeyX',
  keyY: 'KeyY',
  keyZ: 'KeyZ',
  digit0: 'Digit0',
  digit1: 'Digit1',
  digit2: 'Digit2',
  digit3: 'Digit3',
  digit4: 'Digit4',
  digit5: 'Digit5',
  digit6: 'Digit6',
  digit7: 'Digit7',
  digit8: 'Digit8',
  digit9: 'Digit9',
  minus: 'Minus',
  equal: 'Equal',
  bracketLeft: 'BracketLeft',
  bracketRight: 'BracketRight',
  backslash: 'Backslash',
  semicolon: 'Semicolon',
  quote: 'Quote',
  backquote: 'Backquote',
  comma: 'Comma',
  period: 'Period',
  slash: 'Slash',
  arrowUp: 'ArrowUp',
  arrowDown: 'ArrowDown',
  arrowLeft: 'ArrowLeft',
  arrowRight: 'ArrowRight',
  home: 'Home',
  end: 'End',
  pageUp: 'PageUp',
  pageDown: 'PageDown',
  tab: 'Tab',
  capsLock: 'CapsLock',
  shiftLeft: 'ShiftLeft',
  shiftRight: 'ShiftRight',
  controlLeft: 'ControlLeft',
  controlRight: 'ControlRight',
  altLeft: 'AltLeft',
  altRight: 'AltRight',
  enter: 'Enter',
  space: 'Space',
  backspace: 'Backspace',
  delete: 'Delete',
  escape: 'Escape',
  mouseLeft: 'MouseLeft',
  mouseRight: 'MouseRight',
}

export const buttons = new Set([
  'keyA',
  'keyB',
  'keyC',
  'keyD',
  'keyE',
  'keyF',
  'keyG',
  'keyH',
  'keyI',
  'keyJ',
  'keyK',
  'keyL',
  'keyM',
  'keyN',
  'keyO',
  'keyP',
  'keyQ',
  'keyR',
  'keyS',
  'keyT',
  'keyU',
  'keyV',
  'keyW',
  'keyX',
  'keyY',
  'keyZ',
  'digit0',
  'digit1',
  'digit2',
  'digit3',
  'digit4',
  'digit5',
  'digit6',
  'digit7',
  'digit8',
  'digit9',
  'minus',
  'equal',
  'bracketLeft',
  'bracketRight',
  'backslash',
  'semicolon',
  'quote',
  'backquote',
  'comma',
  'period',
  'slash',
  'arrowUp',
  'arrowDown',
  'arrowLeft',
  'arrowRight',
  'home',
  'end',
  'pageUp',
  'pageDown',
  'tab',
  'capsLock',
  'shiftLeft',
  'shiftRight',
  'controlLeft',
  'controlRight',
  'altLeft',
  'altRight',
  'enter',
  'space',
  'backspace',
  'delete',
  'escape',
  'mouseLeft',
  'mouseRight',
])
